import { AppBar, Box, Button, Dialog, DialogTitle, IconButton, Toolbar, Typography } from "@mui/material";
import Head from "next/head";
import MenuIcon from '@mui/icons-material/Menu';
import { useState } from "react";
import { Ball } from "@/components/atoms/Ball";
import { Header } from "@/components/molecules/Header";
import { Footer } from "@/components/molecules/Footer";
import { Layout } from "@/components/organisms/Layout";


export const Home = () => {

    return (
        <>
            <Head>
                <title>Hello world</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <Layout>
                <div style={{
                    width: '100px',
                    height: '100px',
                    backgroundColor: 'blue',
                }}></div>
            </Layout>
        </>
    )
}

export default Home;