import { AppBar, Box, Button, Dialog, DialogTitle, IconButton, Toolbar, Typography, useTheme } from "@mui/material";
import Head from "next/head";
import MenuIcon from '@mui/icons-material/Menu';
import { useEffect, useState } from "react";
import { Ball } from "@/components/Ball";
import { useColorMode } from "@/context/ColorMode";
import styles from "@/styles/pages/home/Styles.module.css"

// import styles from '@/styles/pages/Index.module.css'

export const Home = () => {

    const theme = useTheme();
    const colorMode = useColorMode();
    const [open, setOpen] = useState<boolean>(false);

    const handleClick = () => {
        alert("Você clicou")
    }

    return (
        <>
            <Head>
                <title>Matheus Vinicius</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main
                
            >
                <Box
                    sx={{flexGrow: 1}}
                >
                    <header className={styles.header}>
                        <Typography variant="h5" sx={{flexGrow: 1, ml: '10px'}}>M</Typography>

                        {/* <Box
                            sx={{
                                p: '10px',

                            }}
                        > */}
                            <Typography variant="subtitle1" sx={{mr: '20px'}}>
                                <Typography variant="subtitle1" component="span" sx={{mr: '5px'}} color="secondary.main">
                                    01.
                                </Typography>
                                About
                            </Typography>

                            <Typography variant="subtitle1" sx={{mr: '20px'}}>
                                <Typography variant="subtitle1" component="span" sx={{mr: '5px'}} color="secondary.main">
                                    02.
                                </Typography>
                                Experience
                            </Typography>

                            <Typography variant="subtitle1" sx={{mr: '20px'}}>
                                <Typography variant="subtitle1" component="span" sx={{mr: '5px'}} color="secondary.main">
                                    03.
                                </Typography>
                                Work
                            </Typography>

                            <Typography variant="subtitle1" sx={{mr: '20px'}}>
                                <Typography variant="subtitle1" component="span" sx={{mr: '5px'}} color="secondary.main">
                                    01.
                                </Typography>
                                Contact
                            </Typography>

                            <Button variant="outlined" sx={{ color: theme.palette.secondary.main, mr: '20px'}}>RESUME</Button>
                        {/* </Box> */}
                    </header>
                    {/* <AppBar
                        position="static"
                        sx={{
                            backgroundColor: theme.palette.background.default,
                            boxShadow: '',
                            backgroundImage: '',
                        }}

                    >
                    <Toolbar>
                        <IconButton
                            size="large"
                            edge="start"
                            color="inherit"
                            aria-label="menu"
                            sx={{ mr: 2 }}
                        >
                            <MenuIcon />
                        </IconButton>
                        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                            News
                        </Typography>
                        <Button
                            onClick={() => setOpen(true)}
                        color="inherit">Login</Button>
                        </Toolbar>    
                    </AppBar> */}
                </Box>

                <Ball
                    color="#00F"
                >ds</Ball>

                <Button onClick={() => colorMode.toggleColorMode()} >Click</Button>

                <Dialog
                    open={open}
                    // onClose={() => setOpen(false)}
                    disableEscapeKeyDown
                >
                    <DialogTitle>Dialog</DialogTitle>
                    <Button
                        onClick={() => setOpen(false)}
                    >EXIT</Button>
                </Dialog>
            </main>
        </>
    )
}

export default Home;