import Head from 'next/head'
import styles from '@/styles/pages/Index.module.css'
import { AppBar, Box, Button, IconButton, Toolbar, Typography } from '@mui/material';
import { useColorMode } from '@/context/ColorMode';
import { GearSix, GithubLogo, LinkedinLogo } from '@phosphor-icons/react';

export default function Home() {

  const colorMode = useColorMode();

  return (
    <>
      <Head>
        <title>Home - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AppBar
          position='static'
        >
          <Toolbar>
            <Typography variant='h5' sx={{flexGrow: 1}}>Projects</Typography>

            <Box>
              <IconButton
                sx={{
                  borderRadius: '5px',
                }}
              >
                <LinkedinLogo size={32} />
              </IconButton>

              <IconButton>
                <GithubLogo size={32} />
              </IconButton>
            </Box>
          </Toolbar>
        </AppBar>

        <Box
          sx={{
            display: 'flex',
            justifyContent: 'center',
            flexDirection: 'column',
            alignItems: 'center'
          }}
        >
          <Typography variant='h4'>Hello World</Typography>

          <Button
            onClick={() => colorMode.toggleColorMode()}
          >Change Color</Button>

          <GearSix size={64} className={styles.gear} />
        </Box>
      </main>
    </>
  )
}
